command:
  description: Send command to mower. Accepted values are mow, returnToDock and pause
  fields:
    command: 
      description: Command for mower
      example: "mow"
smartmowing:
  description: Enable or disable Smart Mowing. Accepted values are true and false
  fields:
    enable: 
      description: Enable Smart Mow 
      example: "true"